v2.0.2
idom-team/django-idom pull request #108
Opened 2022-10-19 07:06 UTC by Archmonger

## Description

Fixes some type hints I discovered on `view_to_component`.

Not a huge fan of these rapid iterative bugfixes, but this release also comes alongside a non-trivial security warning surrounding `view_to_component(compatibility=True)`

## Checklist:

Please update this checklist as you complete each item:

-   [x] Tests have been included for all bug fixes or added functionality.
-   [x] The `changelog.rst` has been updated with any significant changes, if necessary.
-   [x] GitHub Issues which may be closed by this PR have been linked.

2022-10-20 08:39 UTC, Archmonger commented
I need some support on the return type hint for `view_to_component`

Since the decorator is polymorphic, I can't figure out how to annotate how this decorator can be used with or without parenthesis.

The current annotations do not work properly when parenthesis are used, such as [in our tests](https://github.com/Archmonger/django-idom/blob/0d05e6ed883952ff32f370220e6d4a7564191e5b/tests/test_app/components.py#L383).

2022-10-20 23:45 UTC, rmorshea commented
You'd handle that polymorphic behavior with [`@overload`](https://mypy.readthedocs.io/en/stable/more_types.html#function-overloading). Typing this correctly can tricky. Don't have time to give a full example now, but can help if needed.

2022-10-21 01:16 UTC, Archmonger commented
Support on that would be great.

You can either commit it directly to this branch, or we can push this PR forward and PR proper type hints later.

2022-10-21 17:00 UTC, rmorshea commented
Here's a sample of what the overload might look like:

```python
@overload
def view_to_component(view: Callable | View) -> _ViewComponentConstructor: ...

@overload
def view_to_component(view: None = ..., other_params: Any) -> Callable[[Callable], _ViewComponentConstructor]: ...

# final definition
def view_to_component(view: Callable | View | None = None, other_params: Any) -> _ViewComponentConstructor | Callable[[Callable], _ViewComponentConstructor]: ...
```

2022-10-22 13:04 UTC, Archmonger commented
Dang, overload is pretty neat.

I needed to do some modifications in order for the type hints to also work for use cases such as:

```python
_view_to_component_kwargs = view_to_component(views.view_to_component_kwargs, compatibility=True)
```

I believe I got something pretty solid in terms of type hints.

2022-10-27 22:17 UTC, Archmonger commented
@rmorshea not sure why my local MyPy doesn't generate warnings but GitHub actions does.

2022-10-27 22:37 UTC, rmorshea commented on requirements/check-types.txt
> -django-stubs[compatible-mypy]
You removed this from the requirements file. I think this is causing the issue.

2022-10-27 22:48 UTC, rmorshea commented on requirements/check-types.txt
> -django-stubs[compatible-mypy]
The underlying problem is that, without this, `View` is treated as `Any` and thus causes the signature overlap.

2022-10-28 02:10 UTC, rmorshea requested changes
In general there seem to be a bunch of `type: ignore` comments that could potentially be resolved in a better way. Let's see if we can remove those. If not, could you comment with the reason?

For the ignore comments in our tests, I don't think those are necessary seeing as we don't actually type check our tests. If your IDE is showing type errors in those files, let's add an [exclude pattern](https://mypy.readthedocs.io/en/stable/config_file.html#confval-exclude) to our config.

2022-10-28 02:14 UTC, rmorshea commented on src/django_idom/components.py
> +            view_html = await view(request_obj, *_args, **_kwargs)  # type: ignore
This seems to be a problem because the type of `view` ought to be `type[View]` instead of a `View` instance.

2022-10-28 02:14 UTC, rmorshea commented on src/django_idom/components.py
> +            )  # type: ignore
Let's `typing.cast` the initial value of converted view to `VdomDict` so we can remove this ignore comment.

2022-10-31 22:18 UTC, Archmonger commented
I think it's worthwhile to keep the ignores in `tests/*`. It actually helped out in letting me detect when the `@view_to_component` decorator type hints were broken.

2022-10-31 22:59 UTC, rmorshea commented
Perhaps we should run `mypy` on our tests then?

2022-10-31 23:25 UTC, Archmonger commented
Done

2022-11-01 23:09 UTC, Archmonger commented
Hopefully we can push this out today. I'd like to get the VTC security warning on the docs ASAP

2022-11-02 03:08 UTC, rmorshea requested changes

2022-11-02 03:09 UTC, rmorshea approved these changes

2022-11-02 03:22 UTC, rmorshea commented
I think we can merge this, but I'm a little uncertain whether running MyPy against our test suite is the right move. I'm worried that the benefits of doing so don't outweigh the burden it might places on potential contributors. MyPy allows for per-module configuration, so perhaps, in a follow-up PR, we could tweak our MyPy configuration for our tests to be more lenient than the configuration we apply to our tests.

2022-11-02 06:10 UTC, Archmonger commented
I don't mind not running the test suite on the `tests/` folder via workflows. But I'd like to be able to verbosely see errors when actually typing the tests.

Increasing test leniency might reduce the API/typehint bugs I manually catch while writing test.

2022-11-02 06:32 UTC, rmorshea commented
MyPy is pretty configurable so I'm pretty sure we could strike a nice balance.

2022-11-02 06:47 UTC, merged