Auto populate IDOM component registry
idom-team/django-idom pull request #24
Opened 2021-10-29 05:38 UTC by Archmonger

When Django first loads, attempt to populate the IDOM component registry.

This design was inspired by [`django_compressor`](https://github.com/django-compressor/django-compressor). See https://github.com/idom-team/django-idom/discussions/20 for more details.

2021-10-29 19:22 UTC, Archmonger commented
The only caveat to this design is it seems to inconsistently break `django-silk`.
Currently digging into root cause on that.

2021-10-30 03:59 UTC, Archmonger commented
Converting to draft while I debug django-silk compatibility

2021-10-30 05:33 UTC, Archmonger commented
It was too much of a hassle to fix `django-silk` non-HTTP request renders (silk's source is messy), so I opted to rely on regex to parse component names.

Functionally this implementation should be equivalent.

2021-11-01 03:23 UTC, rmorshea requested changes

2021-11-01 03:23 UTC, rmorshea commented on src/django_idom/utils.py
> +        )
Can you pull this regex out into a global variable and write some basic unit tests for it?

2021-11-01 03:23 UTC, rmorshea commented on src/django_idom/utils.py
> +            r"{% *idom_component ((\"[^\"']*\")|('[^\"']*')).*%}"
Could you change `.*` to `.*?`

2021-11-01 08:22 UTC, Archmonger commented
I resolved the two comments, and additionally I've created a `tests` folder since we'll likely add more in the future.

Django mandates this test folder naming scheme, but it does feel a bit awkward though since our test app is also called `tests`. Might be something worth changing in a future PR?

2021-11-01 20:40 UTC, rmorshea requested changes
LGTM besides a few more minor nits

2021-11-01 20:40 UTC, rmorshea commented on src/django_idom/utils.py
> +COMPONENT_REGEX_PATTERN = r"{% *idom_component ((\"[^\"']*\")|('[^\"']*')).*?%}"
You should be able to just do `COMPONENT_REGEX_PATTERN = re.compile(...)` so you don't have to re-compile every time its used.

2021-11-01 20:40 UTC, rmorshea commented on tests/test_app/tests/test_regex.py
> +        self.assertRegex(r'{%idom_component "my.component"%}', COMPONENT_REGEX_PATTERN)
Maybe this could be done in a for-loop?

2021-11-01 20:41 UTC, rmorshea commented
Once we get this in I think we can do a release.

2021-11-01 22:49 UTC, Archmonger commented
Completed!

2021-11-02 07:44 UTC, rmorshea approved these changes

2021-11-02 07:46 UTC, merged