Allow whitespace characters within component regex
idom-team/django-idom pull request #96
Opened 2022-09-16 22:40 UTC by Archmonger

## Description

I realized some handlebars formatters will add indentation and newlines. Therefore, I've made the component regex a bit more robust to handle those situations.

## Checklist:

Please update this checklist as you complete each item:

-   [X] Tests have been included for all bug fixes or added functionality.
-   [ ] The `changelog.rst` has been updated with any significant changes, if necessary.
-   [X] GitHub Issues which may be closed by this PR have been linked.

2022-09-17 01:25 UTC, rmorshea commented on src/django_idom/utils.py
> +_component_kwargs = r"((.*?|\s*?)*)"
While we're at it. Can we add names to these groups with `(?P<...>)`? Will just help out readability when matching.

2022-09-18 18:09 UTC, rmorshea commented
In usages of the regex pattern you can use `pattern.match(...).group(group_name)` instead of grabbing them by index.

2022-09-18 20:53 UTC, Archmonger commented
`pattern.match(...).group(group_name)` only works with single objects. To "find all" I needed to use `finditer` and `groupdict`.

I don't believe I'm using the index anywhere anymore.

2022-09-18 23:59 UTC, rmorshea commented on src/django_idom/utils.py
>                          continue
This is always going to be true. If the iterable is empty `update()` will do nothing anyway.
```suggestion
```

2022-09-19 00:00 UTC, rmorshea requested changes

2022-09-19 00:00 UTC, rmorshea commented on src/django_idom/utils.py
>                          continue
No need for this check. The `update()` will do nothing if the iterable is empty
```suggestion
```

2022-09-19 00:02 UTC, rmorshea commented on src/django_idom/utils.py
> +                            match.groupdict()["path"].replace('"', "").replace("'", "")
I'm pretty sure you can just do this if you only need one named group:
```suggestion
                            match.group("path").replace('"', "").replace("'", "")
```

2022-09-19 20:11 UTC, rmorshea approved these changes

2022-09-19 20:38 UTC, merged